services:
  configurator:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      - LETSENCRYPT_HOST=new.am32.ca
      - VIRTUAL_HOST=new.am32.ca
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"
    networks:
      - proxy
      - conf
  cache:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
networks:
  conf:
  proxy:
    external: true
volumes:
  cache: