services:
  configurator:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-am32.ca}
      - VIRTUAL_HOST=${VIRTUAL_HOST:-am32.ca}
      - VIRTUAL_PORT=${VIRTUAL_PORT:-3000}
      - REDIS_HOST=${REDIS_HOST:-cache}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "8080:3000"
    networks:
      - proxy
      - conf
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
  cache:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    #volumes:
      #- cache:/data
networks:
  conf:
  proxy:
    external: true
volumes:
  cache:
  redisinsight: